### ISSUE TITLE
User can rate a student.

### ISSUE THREAD

**Issue by gdegas** [gdegas/Rate-My-Child#2]
# Motivation
A user can rate a child's behavior for that day.

# Tasks
- [x] Create a wireframe
- [x] Create a new Reports.sql file and create a new table 'reports' that includes: id, date, color, parent_name, student_name, comments.
- [x] Define a function in 'crud-reports.js' that uses knex to send a query to insert a report into table 'reports'
- [x] Require crud-reports.js in index.js
- [x] Register a POST route handler to '/reports' to use knex function that inserts data into table reports
- [x] Define a function on 'main.js' that uses fetch with a method post to sent data from browser
- [x] Write HTML for report logging view.
- [x] define that funciton that uses knex to find a student by id. 
- [x] register a get handler to find student by id, route parameters (student/:id)
- [x] define a function that fetches a student by id
- [x] define a function that takes a student and updates the report form to add student name and value of hidden input to student id.
- [x] Add event listener to student list to view swap to report page
- [x] add event listener to form tag that gets input values and uses fetch to send the data.
    - [x] Write a function that get the input value of radios

# Wireframe
![ratemychild issue-3](https://user-images.githubusercontent.com/26953295/28227987-5e6a2f02-6891-11e7-82fe-f21c6010b5e5.png)
