### ISSUE TITLE
User can send an SMS of student report to parent

### ISSUE THREAD

**Issue by gdegas** [gdegas/Rate-My-Child#4]
# Motivation
Parent can get daily notifications of child's behavior for that day

# Tasks
- [x] Create a wireframe
- [x] Install Twilio as a dependency
- [x] Create a new JS file with Twilio authen token credentials and export the object
- [x] Add JS file with tokens to .gitignore
- [x] In 'index.js' require Twilio and the JS file with authentication tokens.
- [x] Use the Twilio app to send an SMS and register it in my post handler for /reports.
- [x] Create a checkbox with a label saying 'Send text to parent' that is automatically checked.
- [x] define a function that uses fetch with a parameter as a query string set to a boolean based on whether my checkbox is checked or not.
- [x] Add a link to return to students at the top of the page.
- [x] Define a class hashrouter and add id attributes to my views that listens to when user changes hashes.
- [x] Add a date to the add-report view
- [x] set HTML5 form validation for input fields on the add report view and add student view.
- [x] Create a reset method on the form object in your hashchanges.

# Wireframe 
![rate my child issue-4](https://user-images.githubusercontent.com/26953295/28387194-017f61b8-6c83-11e7-98ff-5c7920a05974.png)
